"""Stale developer build/dependency directories (report-only).

Projects accumulate large, regenerable directories — ``node_modules``,
``.venv``, ``target``, ``build`` — that can be safely rebuilt by the project's
build tool. When the *project itself* has not been touched in a long time,
those directories are almost certainly dead weight.

This cleaner only ever **reports** such directories (with their size and a hint
on how to reclaim them). It never deletes them: a directory that looks like
build output to us might be something the user still cares about, and deletion
is always the user's deliberate call. The scan is deliberately shallow and
capped so it stays fast on large source trees.
"""

from __future__ import annotations

import os
import time
from pathlib import Path
from typing import Iterable, Optional

from cleanix.cleaners.base import Cleaner
from cleanix.core.models import CleanableItem
from cleanix.core.platform import ALL
from cleanix.core.utils import expand


class ProjectCruftCleaner(Cleaner):
    id = "project_cruft"
    name = "Stale project build/dependency dirs"
    description = (
        "Regenerable build/dependency dirs (.venv, node_modules, target, "
        "build, .tox, .gradle) in projects untouched for months (report only)"
    )
    requires_root = False
    # Developer cruft looks the same everywhere.
    platforms = (ALL,)

    # Directory names we treat as regenerable build/dependency output. Note
    # ``__pycache__`` is intentionally excluded — it is ubiquitous and noisy,
    # and handled by the build-litter cleaner instead.
    _CRUFT_DIRS = {
        ".venv", "venv", "node_modules", "target", ".tox", "build", ".gradle",
    }

    # Defaults mirror the intended ``Config`` fields (see integration notes),
    # read defensively via getattr so this module works before config is wired.
    _DEFAULT_SCAN_DIRS = ["~/Projects", "~/src", "~/dev", "~/code", "~/git"]
    _DEFAULT_STALE_DAYS = 120.0

    # Guard rails so a scan of a huge source tree can never run away.
    _MAX_DEPTH = 6      # directory levels below each scan root
    _MAX_ITEMS = 200    # total cruft dirs surfaced across all roots

    def find_items(self) -> Iterable[CleanableItem]:
        scan_dirs = getattr(
            self.config, "project_scan_dirs", self._DEFAULT_SCAN_DIRS
        )
        try:
            stale_days = float(
                getattr(self.config, "project_stale_days", self._DEFAULT_STALE_DAYS)
            )
        except (TypeError, ValueError):
            stale_days = self._DEFAULT_STALE_DAYS

        now = time.time()
        stale_secs = max(0.0, stale_days) * 86400.0
        # A one-element list is a mutable cell shared across roots so the global
        # item cap is enforced over the *whole* scan, not per root.
        count_ref = [0]

        for raw in scan_dirs or []:
            if count_ref[0] >= self._MAX_ITEMS:
                break
            try:
                root = expand(raw)
            except Exception:  # noqa: BLE001 - never let one bad entry crash us
                continue
            try:
                if root.is_symlink() or not root.is_dir():
                    continue
            except OSError:
                continue

            yield from self._scan_root(root, now, stale_secs, count_ref)

    def _scan_root(
        self, root: Path, now: float, stale_secs: float, count_ref: list
    ) -> Iterable[CleanableItem]:
        root_str = str(root)
        base_depth = root_str.rstrip(os.sep).count(os.sep)

        for dirpath, dirs, _files in os.walk(
            root_str, onerror=lambda _e: None, followlinks=False
        ):
            if count_ref[0] >= self._MAX_ITEMS:
                dirs[:] = []
                return

            depth = dirpath.rstrip(os.sep).count(os.sep) - base_depth
            if depth >= self._MAX_DEPTH:
                dirs[:] = []
                continue

            # Surface (and prune) any cruft dirs at this level.
            for name in list(dirs):
                if name not in self._CRUFT_DIRS:
                    continue
                dirs.remove(name)  # never descend into build output
                cruft = os.path.join(dirpath, name)
                try:
                    if os.path.islink(cruft):
                        continue
                except OSError:
                    continue
                if not self._is_stale(dirpath, cruft, now, stale_secs):
                    continue
                item = self.report_item(
                    cruft,
                    f"Stale build/dependency dir: {cruft}",
                    hint=(
                        "safe to delete; regenerated by your build tool "
                        "(npm install / venv / cargo build)"
                    ),
                )
                if item is not None:
                    count_ref[0] += 1
                    yield item
                    if count_ref[0] >= self._MAX_ITEMS:
                        dirs[:] = []
                        return

            # Skip hidden dirs (except the named cruft ones, already handled)
            # and never follow symlinked subdirectories.
            pruned = []
            for d in dirs:
                if d.startswith(".") and d not in self._CRUFT_DIRS:
                    continue
                try:
                    if os.path.islink(os.path.join(dirpath, d)):
                        continue
                except OSError:
                    continue
                pruned.append(d)
            dirs[:] = pruned

    def _is_stale(
        self, project_dir: str, cruft: str, now: float, stale_secs: float
    ) -> bool:
        """True if the project (or, failing that, the cruft dir) is old."""
        signal = self._project_recent_mtime(project_dir)
        if signal is None:
            try:
                signal = os.lstat(cruft).st_mtime
            except OSError:
                return False
        return (now - signal) > stale_secs

    def _project_recent_mtime(self, project_dir: str) -> Optional[float]:
        """Most-recent mtime of the project's own dir and its immediate,
        non-cruft children — a cheap "when was this last worked on" signal.

        Shallow on purpose: a build touches ``node_modules`` but not the
        source, so ignoring cruft dirs gives the real activity time without a
        deep, slow recursion.
        """
        newest: Optional[float] = None
        try:
            newest = os.lstat(project_dir).st_mtime
        except OSError:
            newest = None
        try:
            with os.scandir(project_dir) as it:
                for entry in it:
                    if entry.name in self._CRUFT_DIRS:
                        continue
                    try:
                        m = entry.stat(follow_symlinks=False).st_mtime
                    except OSError:
                        continue
                    if newest is None or m > newest:
                        newest = m
        except OSError:
            pass
        return newest
